# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdevp',
                'doc_host': 'https://AzulEren.github.io',
                'git_url': 'https://github.com/AzulEren/nbdevp',
                'lib_path': 'nbdevp'},
  'syms': {'nbdevp.core': {'nbdevp.core.foo': ('core.html#foo', 'nbdevp/core.py')}}}
